In [7]:
from utils_fs_v2 import DataGenerator_res2
import jax.numpy as jnp
import jax.random as random
from jax import vmap
from jax.tree_util import tree_flatten, tree_unflatten, register_pytree_node, \
    tree_flatten_with_path, tree_structure, tree_map

In [11]:
# domain_bounds = jnp.array([0.,1.])
# single_domains = jnp.array([[0.,0.4],[0.6,1.]])
# double_domains = jnp.array([[0.4,0.6]])

domain_bounds = jnp.array([0.,2.])
single_domains = jnp.array([[0.,0.4],[0.6,1.],[1.333,2.0]])
double_domains = jnp.array([[0.4,0.6],[1.,1.333]])
D = DataGenerator_res2(domain_bounds,single_domains,double_domains,10)

In [12]:
# D.single_domain_point_dict

In [13]:
def show_example(structured):
  flat, tree = tree_flatten(structured)
  unflattened = tree_unflatten(tree, flat)
  print(f"{structured=}\n  {flat=}\n  {tree=}\n  {unflattened=}")

In [14]:
show_example(D.single_domain_point_dict)

structured=[{'res_pts': Array([[0.34768867]], dtype=float32), 'uni_pts': Array([[0.06492133]], dtype=float32)}, {'res_pts': Array([[0.84995735]], dtype=float32), 'uni_pts': Array([[0.63279486]], dtype=float32)}, {'res_pts': Array([[1.8789763]], dtype=float32), 'uni_pts': Array([[1.9840243],
       [1.5907514]], dtype=float32)}]
  flat=[Array([[0.34768867]], dtype=float32), Array([[0.06492133]], dtype=float32), Array([[0.84995735]], dtype=float32), Array([[0.63279486]], dtype=float32), Array([[1.8789763]], dtype=float32), Array([[1.9840243],
       [1.5907514]], dtype=float32)]
  tree=PyTreeDef([{'res_pts': *, 'uni_pts': *}, {'res_pts': *, 'uni_pts': *}, {'res_pts': *, 'uni_pts': *}])
  unflattened=[{'res_pts': Array([[0.34768867]], dtype=float32), 'uni_pts': Array([[0.06492133]], dtype=float32)}, {'res_pts': Array([[0.84995735]], dtype=float32), 'uni_pts': Array([[0.63279486]], dtype=float32)}, {'res_pts': Array([[1.8789763]], dtype=float32), 'uni_pts': Array([[1.9840243],
       [1.59

In [6]:
def foo(xs):
    return jnp.dot(xs,jnp.arange(3))

Array(10, dtype=int32)

In [6]:
dict.append({'H': 0})

AttributeError: 'dict' object has no attribute 'append'

In [3]:
D.domain_bounds

Array([0., 2.], dtype=float32)

In [4]:
D.single_local_points

Array([2000, 2000, 3335], dtype=int32)

In [5]:
D.double_local_points


Array([1000, 1665], dtype=int32)

In [6]:
D.total_points

Array(10000, dtype=int32)

In [4]:
# domains = jnp.array([[0.0,0.6],[0.4,1.]])
# minval = jnp.array([0.0,0.4])
# maxval = jnp.array([0.6,1.0])
minval = 0.0
maxval = 1.5
key = random.PRNGKey(56)
v = random.uniform(key,(100,1),minval = minval, maxval = maxval)
vs = jnp.sort(v)

In [5]:
vs

Array([[1.04353237e+00],
       [7.84686327e-01],
       [9.20103371e-01],
       [5.47857285e-01],
       [1.82814002e-01],
       [9.59630013e-02],
       [5.69343388e-01],
       [1.13290715e+00],
       [9.12416160e-01],
       [1.20169997e+00],
       [5.57086766e-01],
       [1.18761063e-02],
       [2.21120775e-01],
       [1.22936606e+00],
       [1.46070778e-01],
       [1.45071959e+00],
       [2.67673373e-01],
       [2.33472884e-01],
       [1.49199307e+00],
       [6.38048708e-01],
       [9.04464483e-01],
       [9.79837775e-02],
       [2.93756604e-01],
       [1.27967310e+00],
       [1.25155699e+00],
       [1.48658800e+00],
       [3.54681015e-01],
       [1.20352411e+00],
       [8.53353381e-01],
       [1.33028960e+00],
       [1.20087218e+00],
       [1.39520526e+00],
       [1.10161138e+00],
       [8.72932971e-01],
       [1.30292451e+00],
       [7.13308811e-01],
       [6.85262203e-01],
       [7.91165650e-01],
       [8.93435061e-01],
       [9.56022084e-01],


In [6]:
jnp.ravel(vs).astype(jnp.int32)

Array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int32)

In [16]:
key = random.PRNGKey(42)
keys = random.split(key,4)

In [17]:
keys

Array([[2954079971, 2575172198],
       [1139032965, 1035738655],
       [3276725750, 1223413151],
       [ 173471767,   13772463]], dtype=uint32)

In [18]:
key

Array([ 0, 42], dtype=uint32)

In [3]:
def foo(x):
    return x + 1

In [4]:
v = jnp.arange(10)
vmap(foo)(v)

Array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [5]:
A, B, C, D = 2, 3, 4, 5
x = jnp.ones((A, B))
y = jnp.ones((B, C))
z = jnp.ones((C, D))
def foo(tree_arg):
    x, (y, z) = tree_arg
    return jnp.dot(x, jnp.dot(y, z))
tree = (x, (y, z))
print(foo(tree))


[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [6]:
from jax import vmap
K = 6  # batch size
x = jnp.ones((K, A, B))  # batch axis in different locations
y = jnp.ones((B, K, C))
z = jnp.ones((C, D, K))
tree = (x, (y, z))
vfoo = vmap(foo, in_axes=((0, (1, 2)),))
print(vfoo(tree).shape)
# (6, 2, 5)

(6, 2, 5)


In [10]:
import jax
import jax.numpy as jnp

def process_slice(v,idx):
    # Your processing logic here, e.g., multiply by 2
    return v[idx] * 2

# Original input vector
input_vector = jnp.array([1, 2, 3, 4, 10])
# input_vector2 = jnp.array([-6,-7,-8])

# Indices for slicing the input vector
slice_indices = jnp.array([[0,1],[1,2],[2,3],[3,4],[4,5]])

# Slice the input vector based on the indices
sliced_inputs = input_vector[slice_indices]

# Process the sliced inputs (multiply by 2 in this example)
# processed_sliced_inputs = jax.vmap(process_slice,(None,0,0))(input_vector,slice_indices,input_vector2)
processed_sliced_inputs = jax.vmap(process_slice,(None,0))(input_vector,slice_indices)
print(processed_sliced_inputs)

# # Combine the processed slices back into the original shape
# output_vector = jnp.zeros_like(input_vector)
# output_vector = jax.ops.index_update(output_vector, slice_indices, processed_sliced_inputs)

# print(output_vector)  # Output: [2 2 6 4 10]


[[ 2  4]
 [ 4  6]
 [ 6  8]
 [ 8 20]
 [20 20]]


In [26]:
def func(a,b):
    return a * b

def wrapper(a,b):
    return vmap(func,(None,0))(a,b)

In [27]:
M = jnp.arange(9).reshape((3,3))
v = jnp.arange(3)

In [28]:
vmap(wrapper,(0,0))(v,M)

Array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16]], dtype=int32)